enum TodoActionType {
  REQUEST_TODO_LIST = "REQUEST_TODO_LIST",
  REQUEST_TODO_LIST_SUCCESS = "REQUEST_TODO_LIST_SUCCESS",
  REQUEST_TODO_LIST_ERROR = "REQUEST_TODO_LIST_ERROR",
  
  REQUEST_ADD_TODO_LIST = "ADD_TODO_LIST",
  REQUEST_ADD_TODO_LIST_SUCCESS = "ADD_TODO_LIST_SUCCESS",
  REQUEST_ADD_TODO_LIST_ERROR = "ADD_TODO_LIST_ERROR",

  REQUEST_DELETE_TODO_LIST = "DELETE_TODO_LIST",
  REQUEST_DELETE_TODO_LIST_SUCCESS = "DELETE_TODO_LIST_SUCCESS",
  REQUEST_DELETE_TODO_LIST_ERROR = "DELETE_TODO_LIST_ERROR",
}

export default TodoActionType;